# Generated by Django 5.0 on 2024-01-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('XXL', 'XX-Large')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Grey', 'Grey'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green')], default='not specified', max_length=30),
        ),
    ]
