# Generated by Django 5.0 on 2024-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review_date_posted_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embroidery_location',
            field=models.CharField(blank=True, choices=[('UL', 'Upper Left'), ('LL', 'Lower Left'), ('C', 'Centre'), ('UR', 'Upper Right'), ('LR', 'Lower Right')], default='C', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='embroidery_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
