# Generated by Django 5.0 on 2024-01-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='embroidery_text',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
