# Generated by Django 5.0 on 2024-01-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='colour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='embroidery_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='embroidery_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
